---
- hosts: all
  become: true

  handlers:
    - name: Start docker
      service: name=docker state=started

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: yes
    
    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"

    - name: Add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

    - name: Install docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
      notify: Start docker
