version: '3'

networks:
  services:

volumes:
  jenkins-data:
  jenkins-docker-certs:
  docker-registry:
  prom-data:
  grafana-data:

# TODO: nginx
services:

  jenkins:
    build:
      context: .
    container_name: jenkins
    restart: always
    networks:
      - services
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    image: docker:dind
    container_name: jenkins_docker
    privileged: true
    restart: always
    networks:
      services:
        aliases: 
          - docker
    ports:
      - 2376:2376
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    # TODO: make it cleaner
    command:
      - 'mkdir /etc/docker'
      - 'echo "{ \"insecure-registries\": [\"http://docker-registry:5000\"] }" > /etc/docker/daemon.json'

  docker-registry:
    image: registry
    container_name: docker_registry
    restart: always
    networks:
      - services
    ports:
      - 5000:5000
    volumes:
      - docker-registry:/var/lib/registry

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    networks:
      - services
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
