{
 "title": "Demo App Golden Signals",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate(requests_total[1m]))", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Total By Handler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Per Container",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_memory_usage_bytes{name=~\"web|nginx\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    { "expr": "machine_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage Per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{name=~\"web|nginx\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Error Rate By Handler",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(requests_total{code=~\"4..|5..\"}[1m])) / sum by (handler) (rate(requests_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration By Handler",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(requests_duration_ms_sum{code=~\"2..\"}[1m])) / sum by (handler) (rate(requests_duration_ms_count{code=~\"2..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=~\"web|nginx\"}[1m]) / scalar(sum(machine_cpu_cores))) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}